CREATE DATABASE IF NOT EXISTS item_db CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS auth_db CHARACTER SET utf8;

CREATE USER 'item_user'@'%' IDENTIFIED BY 'item-pw';
CREATE USER 'auth_user'@'%' IDENTIFIED BY 'auth-pw';

GRANT SELECT, INSERT, CREATE, ALTER, DROP, LOCK TABLES, CREATE TEMPORARY TABLES, DELETE, UPDATE, EXECUTE ON item_db .* TO 'item_user'@'%';
GRANT SELECT, INSERT, CREATE, ALTER, DROP, LOCK TABLES, CREATE TEMPORARY TABLES, DELETE, UPDATE, EXECUTE ON auth_db .* TO 'auth_user'@'%';

