server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth-pw
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  jwt:
    secret: "SHUSHHH!"
