server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/item_db
    username: item_user
    password: item-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
client:
  auth:
    base-url: http://auth:8095
